//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhine
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY
    {
        public DELIVERY()
        {
            this.UNITs = new HashSet<UNIT>();
            this.UNITs1 = new HashSet<UNIT>();
        }
    
        public decimal DELIVERYID { get; set; }
        public string DELIVERYNUMBER { get; set; }
        public decimal SHIPFROM { get; set; }
        public decimal SHIPTO { get; set; }
        public Nullable<System.DateTime> SHIPDATE { get; set; }
        public Nullable<System.DateTime> DELIVERYDATE { get; set; }
        public string CUSTORDER { get; set; }
        public Nullable<decimal> SHIPFROMLOGID { get; set; }
        public Nullable<decimal> SHIPTOLOGID { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public System.DateTime UPDATEDDATE { get; set; }
        public Nullable<decimal> DELIVERYSTATUS { get; set; }
    
        public virtual ICollection<UNIT> UNITs { get; set; }
        public virtual ICollection<UNIT> UNITs1 { get; set; }
    }
}
