//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhine
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCLUDE
    {
        public decimal UNITID { get; set; }
        public decimal INCNAMEID { get; set; }
        public string INCNUMBER { get; set; }
        public Nullable<decimal> UNITLOGID { get; set; }
    
        public virtual UNIT UNIT { get; set; }
    }
}
