//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HPDDPRODEntities : DbContext
    {
        public HPDDPRODEntities()
            : base("name=HPDDPRODEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DELIVERY> DELIVERies { get; set; }
        public DbSet<PRODINFO> PRODINFOes { get; set; }
        public DbSet<UNIT> UNITs { get; set; }
        public DbSet<INCLUDE> INCLUDEs { get; set; }
    }
}
