//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhine
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT
    {
        public UNIT()
        {
            this.INCLUDEs = new HashSet<INCLUDE>();
        }
    
        public decimal UNITID { get; set; }
        public string MSN { get; set; }
        public Nullable<decimal> SUPPLYDELIVERYID { get; set; }
        public Nullable<decimal> SUPPLYPACKAGEID { get; set; }
        public Nullable<decimal> DELIVERYID { get; set; }
        public Nullable<decimal> PACKAGEID { get; set; }
        public Nullable<System.DateTime> MANUFDATE { get; set; }
        public decimal PRODINFOID { get; set; }
        public Nullable<decimal> SHIPFROMLOGID { get; set; }
        public Nullable<decimal> SHIPTOLOGID { get; set; }
        public decimal UNITSTATUS { get; set; }
        public System.DateTime UPDATEDDATE { get; set; }
    
        public virtual DELIVERY DELIVERY { get; set; }
        public virtual DELIVERY DELIVERY1 { get; set; }
        public virtual PRODINFO PRODINFO { get; set; }
        public virtual ICollection<INCLUDE> INCLUDEs { get; set; }
    }
}
